export { default as Footer } from './Footer';
export { default as Header } from './Header';
export { default as SearchBar } from './SearchBar';
export { default as FoodCards } from './FoodCards';
export { default as FoodCategories } from './FoodCategories';
export { default as DrinkCards } from './DrinkCards';
export { default as DrinkCategories } from './DrinkCategories';
export { default as FoodDetailsCard } from './FoodDetailsCard';
export { default as DrinkRecomendation } from './DrinkRecomendation';
